#!/usr/bin/env bash
# Regenerate src/thread/ffi.rs from ST's C headers.
#
# The bindings must match the wireless coprocessor firmware actually installed
# on CPU2 (stm32wb5x_Thread_FTD_fw.bin), so the sources are pinned to the
# STM32CubeWB release that shipped it. Bump both SHAs together when moving to
# a new stack version, rerun this, and rebuild.
#
# Needs network access on first run. Everything else comes from nixpkgs.
set -euo pipefail

# stm32-mw-wpan: OpenThread public headers + ST's M4<->M0 message-ID enums.
# This is the submodule commit of STM32CubeWB v1.24.0, the stack we install.
WPAN_SHA=1a66948ee871e7665712aa53dd3cbb9a71c4985a
# STM32CubeWB: only for Drivers/CMSIS/Include, which ST's headers include.
CUBE_SHA=788f3c3

out=$(cd "$(dirname "$0")/.." && pwd)/src/thread/ffi.rs
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

echo "fetching ST sources..."
git clone -q --filter=blob:none --no-checkout https://github.com/STMicroelectronics/stm32-mw-wpan.git "$work/wpan"
git -C "$work/wpan" sparse-checkout init --cone
git -C "$work/wpan" sparse-checkout set thread/openthread/stack/include thread/openthread/core/openthread_api
git -C "$work/wpan" fetch -q --depth 1 origin "$WPAN_SHA"
git -C "$work/wpan" checkout -q "$WPAN_SHA"

git clone -q --filter=blob:none --no-checkout https://github.com/STMicroelectronics/STM32CubeWB.git "$work/cube"
git -C "$work/cube" sparse-checkout init --cone
git -C "$work/cube" sparse-checkout set Drivers/CMSIS/Include
git -C "$work/cube" checkout -q "$CUBE_SHA"

cat > "$work/wrapper.h" <<'HDR'
#include <openthread/instance.h>
#include <openthread/ip6.h>
#include <openthread/link.h>
#include <openthread/thread.h>
#include <openthread/dataset.h>
#include <openthread/ping_sender.h>
#include "stm32wbxx_core_interface_def.h"
HDR

nix="nix --extra-experimental-features nix-command --extra-experimental-features flakes"
# newlib headers: ST builds with arm-none-eabi-gcc, so bind against its libc,
# not the host glibc. -fshort-enums matches that toolchain's default and is
# why otError and otDeviceRole are one byte rather than four.
arm=$($nix build --no-link --print-out-paths nixpkgs#gcc-arm-embedded)
inc=$work/wpan/thread/openthread/stack/include
api=$work/wpan/thread/openthread/core/openthread_api

echo "running bindgen..."
$nix run nixpkgs#rust-bindgen -- "$work/wrapper.h" -o "$out" \
  --use-core --ctypes-prefix core::ffi --no-layout-tests \
  --default-enum-style newtype --constified-enum-module 'MsgId_.*' \
  --raw-line '// @generated by tools/gen-thread-bindings.sh -- do not edit.' \
  --raw-line "// stm32-mw-wpan $WPAN_SHA (STM32CubeWB v1.24.0, the stack we install on CPU2)." \
  --raw-line '#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, unnecessary_transmutes)]' \
  --allowlist-type 'otError|otDeviceRole|otIp6Address|otExtAddress|otNeighborInfo|otNeighborInfoIterator' \
  --allowlist-type 'otOperationalDataset|otOperationalDatasetTlvs|otPingSender.*|otRouterInfo' \
  --allowlist-type 'otPanId|otExtendedPanId|otNetworkName|otMeshLocalPrefix|MsgId_.*' \
  -- -target thumbv7em-none-eabihf -fshort-enums -nostdinc \
     -isystem "$(clang -print-resource-dir)/include" \
     -isystem "$arm/arm-none-eabi/include" \
     -I"$inc" -I"$inc/openthread" -I"$api" -I"$work/wpan" \
     -I"$work/cube/Drivers/CMSIS/Include"

echo "wrote $out ($(wc -l < "$out") lines)"
